spring :
  datasource:
    url: jdbc:postgresql://localhost:5432/Seddle
    username: postgres
    password: Harsha@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com:
      postgresql:
        demo1: DEBUG

myProperty:
  name: ranjith
